typography_spectrum: 0.399
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.41343176434747875
  lightness: 0.10223113326355815
  saturation: 0.11560519901104271
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: FuturistSpeaker
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Futurist Gerd Leonhard's intelligent grid
description: Embrace technology but don't become it
purpose: []
