typography_spectrum: 0.399
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.41343176434747875
  lightness: 0.10223113326355815
  saturation: 0.11560519901104271
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Gerd Leonhard
  email: gerd@thefuturesagency.com
  url: www.futuristgerd.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3dc17c43-06e1-4b5b-b3c6-03dbd2e0b98d.jpg
name: 'Futurist, Author, Keynote Speaker, Film Maker'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: FuturistGerd main site
    url: 'http://www.futuristgerd.com'
    type: external
  - name: Technology vs Humanity - Gerd's new book
    url: 'http://www.techvshuman.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2754363c-a950-4b08-9eb1-480ef9c60519.png
title: Futurist Gerd Leonhard's intelligent grid
description: Embrace technology but don't become it
purpose: []
